export const projectFilters = [
    { id: 'all', label: 'All' },
    { id: 'web', label: 'Web app' },
    { id: 'api', label: 'API / Backend' },
    { id: 'game', label: 'Game' },
    { id: 'utility', label: 'Utility' },
]

export const projectsPageItems = [
    {
        id: 'word-chain',
        categories: ['web', 'game'],
        gradient: 'violet',
        title: '끝말잇기 게임',
        description: '나혼자서 할 수 있는 끝말잇기 게임입니다. 연속 기록 시스템과 제한 시간 기능을 포함하고 있습니다.',
        tags: [
            { label: 'React', variant: 'neutral' },
            { label: 'JavaScript', variant: 'info' },
        ],
        status: { type: 'featured', label: 'Featured' },
        meta: [{ type: 'users', text: 'Game' }],
        demoHref: '#',
        codeHref: 'https://github.com',
        demoLabel: 'Live demo',
    },
    {
        id: 'timer',
        categories: ['web', 'utility'],
        gradient: 'emerald',
        title: '타이머 앱',
        description: '다양한 시간 설정을 지원하는 직관적인 타이머 애플리케이션입니다.',
        tags: [
            { label: 'React', variant: 'neutral' },
        ],
        status: { type: 'live', label: 'Live' },
        meta: [{ type: 'users', text: 'Utility' }],
        demoHref: '#',
        codeHref: 'https://github.com',
        demoLabel: 'Live demo',
    },
    {
        id: 'router-study',
        categories: ['web'],
        gradient: 'sunset',
        title: '라우터 학습 프로젝트',
        description: 'React Router의 다양한 기능을 학습하고 구현해 본 프로젝트입니다.',
        tags: [
            { label: 'React Router', variant: 'warning' },
        ],
        status: null,
        meta: [{ type: 'users', text: 'Learning' }],
        demoHref: '#',
        codeHref: 'https://github.com',
        demoLabel: 'View Code',
    },
    {
        id: 'weather-app',
        categories: ['web', 'api'],
        gradient: 'sky',
        title: '날씨 확인 앱',
        description: '전국 250개 측정소의 실시간 데이터를 수집/분석하여 위치 기반 맞춤 알림을 제공하는 PWA 서비스입니다.',
        tags: [
            { label: 'React', variant: 'neutral' },
            { label: 'JavaScript', variant: 'info' },
            { label: 'PWA', variant: 'success' },
        ],
        status: { type: 'featured', label: 'Featured' },
        meta: [{ type: 'users', text: 'Service' }],
        demoHref: '#',
        codeHref: 'https://github.com',
        demoLabel: 'Live demo',
    },
    {
        id: 'todo-list',
        categories: ['web', 'utility'],
        gradient: 'amber',
        title: 'TODO LIST',
        description: '할 일을 관리하고 우선순위를 정할 수 있는 기본적인 투두 리스트 애플리케이션입니다.',
        tags: [
            { label: 'React', variant: 'neutral' },
        ],
        status: null,
        meta: [{ type: 'users', text: 'Utility' }],
        demoHref: '#',
        codeHref: 'https://github.com',
        demoLabel: 'Live demo',
    },
    {
        id: 'emotion-diary',
        categories: ['web'],
        gradient: 'rose',
        title: '감정 일기장',
        description: '오늘의 기분을 기록하고 날짜별로 감정을 관리할 수 있는 다이어리 서비스입니다.',
        tags: [
            { label: 'React', variant: 'neutral' },
            { label: 'JavaScript', variant: 'info' },
        ],
        status: { type: 'live', label: 'Live' },
        meta: [{ type: 'users', text: 'Service' }],
        demoHref: '#',
        codeHref: 'https://github.com',
        demoLabel: 'Live demo',
    },
    {
        id: 'wifi-map',
        categories: ['web', 'api'],
        gradient: 'violet',
        title: '와이파이 찾기',
        description: '사용자 주변의 공공 와이파이 위치를 지도상에 표시해주는 서비스입니다.',
        tags: [
            { label: 'API', variant: 'info' },
            { label: 'Map', variant: 'success' },
        ],
        status: null,
        meta: [{ type: 'users', text: 'Utility' }],
        demoHref: '#',
        codeHref: 'https://github.com',
        demoLabel: 'Live demo',
    },
    {
        id: 'tocobo-project',
        categories: ['web'],
        gradient: 'emerald',
        title: 'Tocobo 프로젝트',
        description: '신동환 님의 Tocobo 프로젝트 클론 코딩 및 구현 작업입니다.',
        tags: [
            { label: 'React', variant: 'neutral' },
        ],
        status: { type: 'featured', label: 'Featured' },
        meta: [{ type: 'users', text: 'Clone' }],
        demoHref: '#',
        codeHref: 'https://github.com',
        demoLabel: 'View Project',
    },
]