export const skillCategories = [
    {
        key: 'frontend',
        iconKey: 'monitor',
        iconColor: '#61DAFB',
        accent: 'frontend',
        title: 'Frontend',
        subtitle: 'React와 JavaScript를 중심으로 사용자 화면을 구현하고 Vite로 빠르게 개발합니다.',
        skills: [
            { name: 'React', percent: 88 },
            { name: 'JavaScript', percent: 86 },
            { name: 'Vite', percent: 78 },
            { name: 'Responsive UI', percent: 82, showPercent: false },
        ],
        tags: ['React', 'JavaScript', 'Vite', 'UI 구현'],
    },
    {
        key: 'backend',
        iconKey: 'server',
        iconColor: '#6DB33F',
        accent: 'backend',
        title: 'Backend',
        subtitle: 'Spring Boot 기반으로 API 흐름과 프론트엔드 연동을 설계하고 구현합니다.',
        skills: [
            { name: 'Spring Boot', percent: 76 },
            { name: 'REST API', percent: 74, showPercent: false },
            { name: 'Frontend ↔ Backend 연결', percent: 80, showPercent: false },
        ],
        tags: ['Spring Boot', 'REST API', '연동 개발'],
    },
    {
        key: 'infra-devops',
        iconKey: 'cloud',
        iconColor: '#2496ED',
        accent: 'devops',
        title: 'Infra / DevOps',
        subtitle: 'Git, Docker, GitHub Actions로 버전 관리와 배포 자동화 흐름을 다룹니다.',
        skills: [
            { name: 'Git / GitHub', percent: 84 },
            { name: 'Docker', percent: 72 },
            { name: 'GitHub Actions', percent: 70, showPercent: false },
            { name: 'CI/CD workflow', percent: 68, showPercent: false },
        ],
        tags: ['Git', 'GitHub Actions', 'Docker', 'CI/CD'],
    },
    {
        key: 'design-collaboration',
        iconKey: 'sparkle',
        iconColor: '#F24E1E',
        accent: 'design',
        title: 'Design & Collaboration',
        subtitle: 'Figma로 화면 구조와 디자인 의도를 이해하고 구현 단계까지 연결합니다.',
        skills: [
            { name: 'Figma', percent: 82 },
            { name: 'Design handoff', percent: 78, showPercent: false },
            { name: 'UI documentation', percent: 74, showPercent: false },
        ],
        tags: ['Figma', '디자인 협업', 'UI 문서화'],
    },
]

export const certifications = [
    {
        key: 'react-js',
        monogram: 'FE',
        brandColor: '#61DAFB',
        title: 'React · JavaScript 중심 화면 개발',
        issuer: 'Frontend Stack',
        year: 'Current',
        detail: '컴포넌트 기반 UI, 상태 흐름, 반응형 화면 구현을 중심으로 프로젝트에 적용하고 있습니다.',
    },
    {
        key: 'spring-api',
        monogram: 'BE',
        brandColor: '#6DB33F',
        title: 'Spring Boot API 연동 경험',
        issuer: 'Backend Stack',
        year: 'Current',
        detail: 'Spring Boot API와 프론트엔드 화면을 연결하고 로그인/서비스 흐름을 구현한 경험이 있습니다.',
    },
    {
        key: 'deploy-flow',
        monogram: 'OPS',
        brandColor: '#2496ED',
        title: 'Git · Docker · GitHub Actions workflow',
        issuer: 'Infra / DevOps Stack',
        year: 'Current',
        detail: '버전 관리, 컨테이너 기반 실행 환경, GitHub Actions를 활용한 자동화 흐름을 학습·적용합니다.',
    },
]